### PR TITLE
Python 3.x release

### PR DESCRIPTION
**Pull request by spapas**
After many changes this should be ready for python 3 - not compatible with python 2 anymore. Has been tested with Python 3.6.

### CODE REVIEW

**Comment by m0n5t3r** [comment]
Is it ok for me to add a note to the readme pointing to your fork and archive this?

**Comment by m0n5t3r** [comment]
thanks, btw :)

**Comment by spapas** [comment]
The problem with forks is that the commits are not displayed in my commit history until they are merged with the master branch. Would you mind if I cloned the repo (without forking) and added a link to this repo ? 

Something like this I mean: https://github.com/spapas/gstats/

Also, could I change the license to MIT or something similar ?

**Comment by spapas** [comment]
Thanks for merging :)

**Comment by m0n5t3r** [comment]
I'm pretty against MIT and the like (something something people being able to take things private and never give back), but I don't care enough about this to protest, go ahead

**Pull request merged**
